In [23]:
import pandas as pd
import os

def cargarDatos():

    # Carpeta donde están los archivos
    carpeta = "../estaciones"

    # Lista para guardar los DataFrames
    dfs = []

    # Recorrer todos los archivos de la carpeta
    for archivo in os.listdir(carpeta):
        if archivo.endswith(".csv") and archivo.startswith("est_"): # Filtrar archivos CSV que comienzan con "est_"
            ruta_completa = os.path.join(carpeta, archivo)
            df = pd.read_csv(ruta_completa)
            dfs.append(df)
            ncols = df.shape[1]
            print(f"Cargado: {archivo} con {ncols} columnas.")

    # Unir todos los DataFrames
    df_clima = pd.concat(dfs, ignore_index=True)

    print("Archivos unidos correctamente.")

    return df_clima

df_clima = cargarDatos()

Cargado: est_19.csv con 21 columnas.
Cargado: est_20.csv con 21 columnas.
Cargado: est_21.csv con 21 columnas.
Cargado: est_22.csv con 21 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_23.csv con 21 columnas.
Cargado: est_24.csv con 21 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (2,3,4,7,8,9,10,12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_25.csv con 21 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (2,3,4,7,8,9,10,12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_26.csv con 21 columnas.
Cargado: est_27.csv con 22 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (2,3,4,7,8,9,10,12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_28.csv con 21 columnas.
Cargado: est_29.csv con 21 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (2,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_30.csv con 22 columnas.

C:\Users\Ismathrn\AppData\Local\Temp\ipykernel_24444\920033625.py:16: DtypeWarning: Columns (2,3,4,7,8,9,10,12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_completa)

Cargado: est_31.csv con 21 columnas.
Archivos unidos correctamente.

Encontramos un comportamiento importante en la carga de datos relacionado a los tipos de valores encontrados en la columnas, y columnas adicionales en las estaciones 27 y 30 por lo que vamos a proceder a realizar un analisis estadistico de las columnas y sus valores.

In [24]:
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11407292 entries, 0 to 11407291
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   fecha               object
 1   hora                object
 2   temperatura         object
 3   velocidad           object
 4   direccion           object
 5   direccion_rosa      object
 6   caudal              object
 7   presion             object
 8   humedad             object
 9   precipitacion       object
 10  precipitacion_real  object
 11  radiacion           object
 12  evapotranspiracion  object
 13  evapo_real          object
 14  nivel               object
 15  puerta_Abierta      bool
 16  bateria_Baja        bool
 17  solar_energia       bool
 18  sensor_Activo       bool
 19  observaciones       object
 20  estacion_sk         int64
 21  estado_Alarma       object
dtypes: bool(4), int64(1), object(17)
memory usage: 1.6+ GB

In [25]:
columnas_estandar = [
    "fecha","hora","temperatura","velocidad","direccion","direccion_rosa",
    "caudal","presion","humedad","precipitacion","precipitacion_real",
    "radiacion","evapotranspiracion","evapo_real","nivel",
    "estado_Alarma",
    "puerta_Abierta","bateria_Baja","solar_energia","sensor_Activo",
    "observaciones","estacion_sk","timestamp"
]

# Asegurarse de que el DataFrame tenga las columnas y en el orden correcto
for col in columnas_estandar:
    if col not in df_clima.columns:
        df_clima[col] = pd.NA

df_clima = df_clima[columnas_estandar] # Asegura que el orden de las columnas sea exactamente el definido.

df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11407292 entries, 0 to 11407291
Data columns (total 23 columns):
 #   Column              Dtype
---  ------              -----
 0   fecha               object
 1   hora                object
 2   temperatura         object
 3   velocidad           object
 4   direccion           object
 5   direccion_rosa      object
 6   caudal              object
 7   presion             object
 8   humedad             object
 9   precipitacion       object
 10  precipitacion_real  object
 11  radiacion           object
 12  evapotranspiracion  object
 13  evapo_real          object
 14  nivel               object
 15  estado_Alarma       object
 16  puerta_Abierta      bool
 17  bateria_Baja        bool
 18  solar_energia       bool
 19  sensor_Activo       bool
 20  observaciones       object
 21  estacion_sk         int64
 22  timestamp           object
dtypes: bool(4), int64(1), object(18)
memory usage: 1.7+ GB

Aunque desde la concatenación ya se agrego la columna estado_Alarma, en integración de bases meteorológicas se recomienda definir un “esquema maestro” y crear columnas faltantes como NA para homogenizar antes de análisis y modelos. Esto se considera buena práctica en integración de datos ambientales y en el uso de DataFrames tipo pandas.

En esta etapa se  realizará la conversión de variables meteorológicas a formato númerico, manteniendo observaciones como texto y las variables lógicas (puerta_Abierta, bateria_Baja, solar_energia, sensor_Activo) como booleanas.

Conversión a numérico + conteo de NaN por variable

estandarizar símbolos de error a NA,

Se usa to_numeric(errors="coerce") para dejar solo valores válidos numéricos y marcar lo demás como faltante.

En climatología se trabaja mucho con NA explícito como marca de “sensor failure / missing observation” en vez de borrar filas.

In [26]:
cols_num = [
    "temperatura","velocidad","direccion","caudal","presion",
    "humedad","precipitacion","precipitacion_real","radiacion",
    "evapotranspiracion","evapo_real","nivel"
]

valores_invalidos = ["", " ", "-", "--", "_", ".", "None", "null", "N/A", "nan", "NaN", "?", "*", "error", "fail"]

for col in cols_num:
    df_clima[col] = (
        df_clima[col]
        .replace(valores_invalidos, pd.NA)
        .str.replace(",", ".", regex=False)
    )
    df_clima[col] = pd.to_numeric(df_clima[col], errors="coerce")

In [27]:
faltantes_global = df_clima[cols_num].isna().mean().sort_values(ascending=False)
print(faltantes_global)

nivel                 0.940653
caudal                0.940159
evapotranspiracion    0.284767
humedad               0.259508
precipitacion         0.251325
presion               0.249937
direccion             0.249159
velocidad             0.248445
evapo_real            0.239865
temperatura           0.197150
precipitacion_real    0.176333
radiacion             0.160438
dtype: float64

nivel y caudal están casi siempre vacíos → son variables muy poco reportadas. En muchos trabajos con redes de estaciones se suelen:
usar solo descriptivamente,
o excluirlas de modelos porque aportan poca información útil (demasiado hueco).

(temperatura, humedad, precipitación, radiación, etc.) tiene entre 16% y 28% de faltantes:

Es un porcentaje alto, pero habitual en datos meteorológicos reales (fallos de sensores, mantenimiento, cortes de energía).

Literaturas sobre series climáticas recomiendan no borrar filas, sino imputar o modelar los NA por métodos apropiados (interpolación temporal, promedios por hora/día, uso de estaciones vecinas).

In [28]:
df_clima.fecha.describe()

count       11407292
unique          5945
top       2019-10-15
freq            3798
Name: fecha, dtype: object

In [29]:
df_clima.sensor_Activo.describe()

count     11407292
unique           2
top          False
freq      11339720
Name: sensor_Activo, dtype: object

En esta etapa se  realizará la conversión de variables meteorológicas a formato númerico, manteniendo observaciones como texto y las variables lógicas (puerta_Abierta, bateria_Baja, solar_energia, sensor_Activo) como booleanas.

Se crea la columna TIMESTAMP para unir los valores de fecha y hora en un formato estandarizado que facilite el analisis posterior y asegure una Estructuración correcta de la dimensión temporal

In [30]:
df_clima["timestamp"] = pd.to_datetime(df_clima["fecha"] + " " + df_clima["hora"], errors="coerce")

porc_nat = df_clima["timestamp"].isna().mean()

print(f"Porcentaje de valores NaT en 'timestamp': {porc_nat}")

Porcentaje de valores NaT en 'timestamp': 0.1344506654164722

Dado que se identifican valores NaT en la secuencia de tiempo es importante revisar estos datos ya que en series temporales es importante no tener saltos que generen errores en el analisis.

In [31]:
df_clima["timestamp"].head()

0   2012-03-28 01:06:28
1   2012-03-28 01:11:28
2   2012-03-28 01:16:31
3   2012-03-28 01:46:31
4   2012-03-28 01:51:35
Name: timestamp, dtype: datetime64[ns]

In [32]:


df_clima[df_clima["timestamp"].isna()][["fecha", "hora"]].head() # Se visualizan las filas con errores

             fecha      hora
7165671  3/28/2012  23:59:59
7165672  3/28/2012  23:54:57
7165673  3/28/2012  23:49:33
7165674  3/28/2012  23:44:33
7165675  3/28/2012  23:39:31

In [33]:
df_clima[df_clima["timestamp"].isna()]["fecha"].unique()[:20]  # Se visualizan las fechas con errores

#df_clima = df_clima.sort_values(["estacion_sk", "timestamp"])

array(['3/28/2012', '3/29/2012', '3/30/2012', '3/31/2012', '4/1/2012',
       '4/2/2012', '4/3/2012', '4/4/2012', '4/25/2012', '4/26/2012',
       '4/27/2012', '4/28/2012', '4/29/2012', '4/30/2012', '5/1/2012',
       '5/2/2012', '5/3/2012', '5/4/2012', '5/5/2012', '5/6/2012'],
      dtype=object)

Aplicamos una mascara para construir un timestampt incluyendo los formatos con "/"
mask_us es una Serie True/False del mismo largo que df_clima.
df_clima.loc[filas, columnas] sirve para:
seleccionar y/o asignar valores en un subconjunto del DataFrame.

In [34]:
mask_us = df_clima["fecha"].str.contains("/")

# Para filas con formato US (con '/')
df_clima.loc[mask_us, "timestamp"] = pd.to_datetime(
    df_clima.loc[mask_us, "fecha"] + " " + df_clima.loc[mask_us, "hora"],
    format="%m/%d/%Y %H:%M:%S",
    errors="coerce"
)

# Para filas con el formato "normal"
df_clima.loc[~mask_us, "timestamp"] = pd.to_datetime(
    df_clima.loc[~mask_us, "fecha"] + " " + df_clima.loc[~mask_us, "hora"],
    errors="coerce"
)

Ahora validamos nuevamente el porcentaje de error en TIMESTAMP

In [35]:
porc_nat = df_clima["timestamp"].isna().mean()

print(f"Porcentaje de valores NaT en 'timestamp': {porc_nat}")

Porcentaje de valores NaT en 'timestamp': 0.0

Con este nuevo porcentaje de error logramos una Estructuración correcta de la dimensión temporal.
Inicialmente, el 13.44% de los timestamps no se podía interpretar por formatos mixtos; se diseñó un tratamiento diferenciado para fechas con / (%m/%d/%Y %H:%M:%S) y fechas con -, logrando 0% de NaT en timestamp.

In [37]:
df_clima = df_clima.sort_values(["estacion_sk", "timestamp"]).reset_index(drop=True) # Ordenar por estación y timestamp

df_clima.head()

,fecha,hora,temperatura,velocidad,direccion,direccion_rosa,caudal,presion,humedad,precipitacion,...,evapo_real,nivel,estado_Alarma,puerta_Abierta,bateria_Baja,solar_energia,sensor_Activo,observaciones,estacion_sk,timestamp
0,2012-03-28,01:06:28,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,0.00,NaN,NaN,False,False,False,False,temperatura: 15.56 - velocidad: 1.79 - direcci...,19,2012-03-28 01:06:28
1,2012-03-28,01:11:28,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,0.00,NaN,NaN,False,False,False,False,temperatura: 15.39 - velocidad: 1.79 - direcci...,19,2012-03-28 01:11:28
2,2012-03-28,01:16:31,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,0.00,NaN,NaN,False,False,False,False,temperatura: 15.39 - velocidad: 2.68 - direcci...,19,2012-03-28 01:16:31
3,2012-03-28,01:46:31,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,0.00,NaN,NaN,False,False,False,False,temperatura: 15.44 - velocidad: 1.79 - direcci...,19,2012-03-28 01:46:31
4,2012-03-28,01:51:35,15.56,NaN,105.0,ESE,NaN,610.06,86.0,0.0,...,0.03,NaN,NaN,False,False,False,False,"velocidad: 0.45,",19,2012-03-28 01:51:35

In [38]:
df_clima["year"] = df_clima["timestamp"].dt.year
df_clima["month"] = df_clima["timestamp"].dt.month
df_clima["day"] = df_clima["timestamp"].dt.day
df_clima["hour"] = df_clima["timestamp"].dt.hour

EDA numérico y temporal mínimo

In [39]:
print(df_clima[cols_num].describe())

        temperatura     velocidad     direccion         caudal       presion  \
count  9.158346e+06  8.573209e+06  8.565064e+06  682629.000000  8.556189e+06
mean   1.782010e+01  7.749400e-01  1.760660e+02       0.144961  5.988805e+02
std    2.932111e+00  3.349856e+00  1.022951e+02       1.086659  1.176757e+01
min   -8.802296e+01 -2.066150e+01 -1.382566e+03       0.000000  0.000000e+00
25%    1.572000e+01  0.000000e+00  9.100000e+01       0.000000  5.921300e+02
50%    1.739000e+01  0.000000e+00  1.580000e+02       0.005400  5.954600e+02
75%    1.967000e+01  1.340000e+00  2.690000e+02       0.040400  6.078500e+02
max    3.817000e+01  1.139900e+02  3.600000e+02      39.962400  9.737300e+02

            humedad  precipitacion  precipitacion_real     radiacion  \
count  8.447013e+06   8.540350e+06        9.395811e+06  9.577126e+06
mean   8.473968e+01   5.201560e+01        2.223300e-02  1.387581e+02
std    1.691731e+01   1.535029e+02        1.710085e+00  2.485696e+02
min    0.000000e+00   0.000000e+00        0.000000e+00 -1.699300e+04
25%    7.900000e+01   0.000000e+00        0.000000e+00  0.000000e+00
50%    8.600000e+01   2.400000e+00        0.000000e+00  0.000000e+00
75%    9.200000e+01   2.340000e+01        0.000000e+00  2.200000e+02
max    6.368800e+02   9.997400e+02        9.906000e+02  1.448000e+03

       evapotranspiracion    evapo_real          nivel
count        8.158868e+06  8.671079e+06  676992.000000
mean         6.335329e+01  2.624995e-02      13.421851
std          1.849291e+02  3.223337e+00      39.720702
min         -9.234848e+00 -1.076368e+00       0.190000
25%          8.000000e-02  0.000000e+00       4.990000
50%          1.250000e+00  0.000000e+00       6.090000
75%          2.640000e+00  0.000000e+00       7.150000
max          9.998800e+02  9.909900e+02     523.190000

Descriptivos por estación (ej. temperatura)

In [40]:
print(df_clima.groupby("estacion_sk")["temperatura"].describe())

                count       mean       std        min    25%    50%    75%  \
estacion_sk
19           787922.0  18.611968  3.019391  10.830000  16.22  17.89  20.89
20           733583.0  17.509152  2.608374   5.610000  15.44  16.94  19.39
21           690236.0  19.890084  2.669421  10.000000  17.83  19.33  21.61
22           827762.0  17.531787  2.619752  11.110000  15.50  16.94  19.17
23                0.0        NaN       NaN        NaN    NaN    NaN    NaN
24           771583.0  17.877066  3.221521   0.220000  15.65  17.50  20.15
25           712697.0  17.806467  2.069840  12.170000  16.22  17.50  19.11
26           762744.0  17.627753  2.517301   0.110000  15.78  17.28  19.11
27           669540.0  18.170171  3.617228 -88.022962  16.39  17.89  19.78
28           802273.0  18.096003  2.383531  10.890000  16.28  17.72  19.67
29           885518.0  17.059279  2.810604   1.330000  14.89  16.39  18.83
30           718353.0  17.911156  3.245638   3.590000  15.44  17.09  20.12
31           796135.0  16.161002  2.678711   5.500000  14.06  15.50  18.00

               max
estacion_sk
19           29.44
20           30.50
21           30.78
22           30.44
23             NaN
24           29.06
25           27.39
26           38.17
27           27.83
28           34.39
29           30.61
30           30.81
31           29.83

Correlación entre variables meteorológicas:

In [41]:
corr = df_clima[cols_num].corr()
print(corr)

                    temperatura  velocidad  direccion    caudal   presion  \
temperatura            1.000000   0.199667   0.397756 -0.047932  0.087292
velocidad              0.199667   1.000000   0.048875       NaN  0.028055
direccion              0.397756   0.048875   1.000000       NaN  0.020909
caudal                -0.047932        NaN        NaN  1.000000       NaN
presion                0.087292   0.028055   0.020909       NaN  1.000000
humedad               -0.466376   0.234605  -0.150784       NaN  0.033250
precipitacion         -0.102742  -0.018103  -0.001296 -0.002608 -0.070531
precipitacion_real    -0.006517   0.000642  -0.000300  0.034472 -0.016445
radiacion              0.598318   0.272857   0.365805       NaN  0.026879
evapotranspiracion    -0.093237  -0.017006   0.004572       NaN -0.087391
evapo_real             0.002232   0.000766   0.002636       NaN -0.009226
nivel                 -0.076996        NaN        NaN  0.535871       NaN

                     humedad  precipitacion  precipitacion_real  radiacion  \
temperatura        -0.466376      -0.102742           -0.006517   0.598318
velocidad           0.234605      -0.018103            0.000642   0.272857
direccion          -0.150784      -0.001296           -0.000300   0.365805
caudal                   NaN      -0.002608            0.034472        NaN
presion             0.033250      -0.070531           -0.016445   0.026879
humedad             1.000000       0.033592            0.012499  -0.294250
precipitacion       0.033592       1.000000            0.010893   0.005125
precipitacion_real  0.012499       0.010893            1.000000  -0.004590
radiacion          -0.294250       0.005125           -0.004590   1.000000
evapotranspiracion -0.005916       0.939037            0.005062   0.008120
evapo_real         -0.002848       0.011099            0.454810   0.004823
nivel                    NaN       0.059462            0.054928        NaN

                    evapotranspiracion  evapo_real     nivel
temperatura                  -0.093237    0.002232 -0.076996
velocidad                    -0.017006    0.000766       NaN
direccion                     0.004572    0.002636       NaN
caudal                             NaN         NaN  0.535871
presion                      -0.087391   -0.009226       NaN
humedad                      -0.005916   -0.002848       NaN
precipitacion                 0.939037    0.011099  0.059462
precipitacion_real            0.005062    0.454810  0.054928
radiacion                     0.008120    0.004823       NaN
evapotranspiracion            1.000000    0.016508       NaN
evapo_real                    0.016508    1.000000       NaN
nivel                              NaN         NaN  1.000000

In [43]:
df_clima = df_clima.sort_values(["estacion_sk", "timestamp"]).reset_index(drop=True)

df_clima["temperatura_interp"] = (
    df_clima.groupby("estacion_sk")["temperatura"]
            .transform(lambda s: s.interpolate(method="linear", limit_direction="both"))
)

In [44]:
df_clima.head()

,fecha,hora,temperatura,velocidad,direccion,direccion_rosa,caudal,presion,humedad,precipitacion,...,solar_energia,sensor_Activo,observaciones,estacion_sk,timestamp,year,month,day,hour,temperatura_interp
0,2012-03-28,01:06:28,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,False,False,temperatura: 15.56 - velocidad: 1.79 - direcci...,19,2012-03-28 01:06:28,2012,3,28,1,15.56
1,2012-03-28,01:11:28,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,False,False,temperatura: 15.39 - velocidad: 1.79 - direcci...,19,2012-03-28 01:11:28,2012,3,28,1,15.56
2,2012-03-28,01:16:31,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,False,False,temperatura: 15.39 - velocidad: 2.68 - direcci...,19,2012-03-28 01:16:31,2012,3,28,1,15.56
3,2012-03-28,01:46:31,NaN,NaN,NaN,X,NaN,NaN,NaN,0.0,...,False,False,temperatura: 15.44 - velocidad: 1.79 - direcci...,19,2012-03-28 01:46:31,2012,3,28,1,15.56
4,2012-03-28,01:51:35,15.56,NaN,105.0,ESE,NaN,610.06,86.0,0.0,...,False,False,"velocidad: 0.45,",19,2012-03-28 01:51:35,2012,3,28,1,15.56